# --- STRØMSPARING OG BATTERI ---
# Aktiver dyp dvale (deep sleep) etter inaktivitet (anbefalt for trådløse tastaturer)


# Tid før dyp dvale i millisekunder (3 600 000 ms = 60 minutter / 1 time)

CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y


# --- OLED-SKJERMER (Kun dersom du har montert skjermer) ---
# CONFIG_ZMK_DISPLAY=y

# --- RGB-BYS (Kun dersom du har montert RGB LED-lys) ---
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y